token        = ""
secret       = ""
zone         = ""
# if name is directory name, don't have to set name
name         = "libsacloud demo"
description  = "libsacloud demo description"
tag          = "libsacloud-test"
cpu          = 1
mem          = 2
# if name is directory name, don't have to set name
hostName     = "libsacloud-test"
password     = "C8#mf92mp!*s"
sshPublicKey = "ssh-rsa AAAA..."
